import Head from 'next/head';
import React from 'react';

import Event from '@/modules/Event';

export default function Home() {
  return (
    <>
      <Head>
        <title>Supermomos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://cdn.jsdelivr.net/npm/daisyui@2.51.3/dist/full.css"
          rel="stylesheet"
          type="text/css"
        />
      </Head>
      <Event />
    </>
  );
}
